import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import { protestRevolution, roboto } from "@/utils/fonts";
import SkeletonThemeProvider from "@/providers/SkeletonThemeProvider";
import ReduxProvider from "@/providers/ReduxProvider";
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  title: "Bloocode-movies",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`$${roboto.variable} ${protestRevolution.variable} 
        font-roboto text-white bg-black`}
      >
        <Toaster />
        <SkeletonThemeProvider>
          <ReduxProvider>
            <Navbar />
            {children}
          </ReduxProvider>
        </SkeletonThemeProvider>
      </body>
    </html>
  );
}
